select * from CG44_CLIFOR
where CG44_PROGR_EF08=1

update CG44_CLIFOR
set CG44_PROGR_EF08='2'
where CG44_PROGR_EF08=1


update MG35_CLIFORCC
set MG35_BICBANCAESTERA='BAPPIT21496'
WHERE  MG35_CCABI='5034'
and MG35_CCCAB='66500'

--select * from mg35_cliforcc 

--where MG35_CCABI='5188'
--and MG35_CCCAB='66500'
----and mg35_tipocf_cg44=0

--update MG35_CLIFORCC

--set MG35_BBAN='',MG35_IBAN='' ,
--MG35_CCABI = '5034', MG35_CCCAB='66500'
--where MG35_CCABI='5188' 
--and MG35_CCCAB='66500'
--and mg35_tipocf_cg44=0

--
-- Calcolo del codice BBAN e del codice IBAN
--
DECLARE @VAR_DITTA		decimal(5)
DECLARE @VAR_TIPOCF		decimal(1)
DECLARE @VAR_CLIFOR		decimal(6)
DECLARE @VAR_CCFORN		char(15)
DECLARE @VAR_CCABI		decimal(5)
DECLARE @VAR_CCCAB		decimal(5)
DECLARE @VAR_BBAN		char(23)
DECLARE @VAR_IBAN		char(34)

DECLARE @STR_ABI		char(5)
DECLARE @STR_CAB		char(5)
DECLARE @STR_CC			varchar(12)
DECLARE @INDEX			smallint
DECLARE @STR_CHAR		char(1)
DECLARE @STR_BBAN		varchar(22)
DECLARE @INT_SOMMA		int
DECLARE @STR_CIN		char(1)
DECLARE @STR_IBAN		varchar(34)
DECLARE @STR_SOMMA		varchar(100)
DECLARE @NEWM			int
DECLARE @R			int

SET NOCOUNT ON

DECLARE CLIFORCC CURSOR KEYSET FOR
SELECT
	MG35_DITTA_CG18,
	MG35_TIPOCF_CG44,
	MG35_CLIFOR_CG44,
	MG35_CCFORN,
	MG35_CCABI,
	MG35_CCCAB,
	MG35_BBAN,
	MG35_IBAN
FROM
	MG35_CLIFORCC
WHERE
	NOT MG35_CCFORN IS NULL AND
	NOT MG35_CCABI IS NULL AND
	NOT MG35_CCCAB IS NULL AND
	MG35_BBAN=''AND
	MG35_IBAN =''
FOR UPDATE

OPEN CLIFORCC

FETCH NEXT FROM CLIFORCC INTO @VAR_DITTA, @VAR_TIPOCF, @VAR_CLIFOR, @VAR_CCFORN, @VAR_CCABI, @VAR_CCCAB, @VAR_BBAN, @VAR_IBAN

WHILE @@FETCH_STATUS = 0
BEGIN
	--
	-- Calcolo il CIN che ottiene il codice BBAN
	--

	SET @STR_ABI = RIGHT('00000' + CONVERT(varchar, @VAR_CCABI), 5)
	SET @STR_CAB = RIGHT('00000' + CONVERT(varchar, @VAR_CCCAB), 5)

	SET @STR_CC = ''
	SET @INDEX = LEN(@VAR_CCFORN)
	WHILE @INDEX > 0
	BEGIN
		SET @STR_CHAR = UPPER(SUBSTRING(@VAR_CCFORN, @INDEX, 1))
		IF (@STR_CHAR >= 'A' AND @STR_CHAR <= 'Z') OR (@STR_CHAR >= '0' AND @STR_CHAR <= '9')
			SET @STR_CC = @STR_CHAR + @STR_CC
		SET @INDEX = @INDEX - 1
	END

	SET @STR_CC = RIGHT('000000000000' + @STR_CC, 12)

	SET @STR_BBAN = @STR_ABI + @STR_CAB + @STR_CC

	SET @INT_SOMMA = 0
	SET @INDEX = 1
	WHILE @INDEX <= LEN(@STR_BBAN)
	BEGIN
		SET @STR_CHAR = SUBSTRING(@STR_BBAN, @INDEX, 1)

		IF (ROUND(@INDEX / 2, 0) * 2) = @INDEX
			SET @INT_SOMMA = @INT_SOMMA + --FUNZIONE PARI
				CASE @STR_CHAR
					WHEN '0' THEN 0
					WHEN '1' THEN 1
					WHEN '2' THEN 2
					WHEN '3' THEN 3
					WHEN '4' THEN 4
					WHEN '5' THEN 5
					WHEN '6' THEN 6
					WHEN '7' THEN 7
					WHEN '8' THEN 8
					WHEN '9' THEN 9
					WHEN 'A' THEN 0
					WHEN 'B' THEN 1
					WHEN 'C' THEN 2
					WHEN 'D' THEN 3
					WHEN 'E' THEN 4
					WHEN 'F' THEN 5
					WHEN 'G' THEN 6
					WHEN 'H' THEN 7
					WHEN 'I' THEN 8
					WHEN 'J' THEN 9
					WHEN 'K' THEN 10
					WHEN 'L' THEN 11
					WHEN 'M' THEN 12
					WHEN 'N' THEN 13
					WHEN 'O' THEN 14
					WHEN 'P' THEN 15
					WHEN 'Q' THEN 16
					WHEN 'R' THEN 17
					WHEN 'S' THEN 18
					WHEN 'T' THEN 19
					WHEN 'U' THEN 20
					WHEN 'V' THEN 21
					WHEN 'W' THEN 22
					WHEN 'X' THEN 23
					WHEN 'Y' THEN 24
					WHEN 'Z' THEN 25
				END
		ELSE
			SET @INT_SOMMA = @INT_SOMMA + --FUNZIONE DISPARI
				CASE @STR_CHAR
					WHEN '0' THEN 1
					WHEN '1' THEN 0
					WHEN '2' THEN 5
					WHEN '3' THEN 7
					WHEN '4' THEN 9
					WHEN '5' THEN 13
					WHEN '6' THEN 15
					WHEN '7' THEN 17
					WHEN '8' THEN 19
					WHEN '9' THEN 21
					WHEN 'A' THEN 1
					WHEN 'B' THEN 0
					WHEN 'C' THEN 5
					WHEN 'D' THEN 7
					WHEN 'E' THEN 9
					WHEN 'F' THEN 13
					WHEN 'G' THEN 15
					WHEN 'H' THEN 17
					WHEN 'I' THEN 19
					WHEN 'J' THEN 21
					WHEN 'K' THEN 2
					WHEN 'L' THEN 4
					WHEN 'M' THEN 18
					WHEN 'N' THEN 20
					WHEN 'O' THEN 11
					WHEN 'P' THEN 3
					WHEN 'Q' THEN 6
					WHEN 'R' THEN 8
					WHEN 'S' THEN 12
					WHEN 'T' THEN 14
					WHEN 'U' THEN 16
					WHEN 'V' THEN 10
					WHEN 'W' THEN 22
					WHEN 'X' THEN 25
					WHEN 'Y' THEN 24
					WHEN 'Z' THEN 23
				END

		SET @INDEX = @INDEX + 1
	END

	SET @STR_CIN = CHAR((@INT_SOMMA % 26) + 65)

	--
	-- Calcolo il checksum del codice IBAN
	--
	SET @STR_IBAN = @STR_CIN + @STR_BBAN + 'IT00'

	SET @STR_SOMMA = ''
	SET @INDEX = 1
	WHILE @INDEX <= LEN(@STR_IBAN)
	BEGIN
		SET @STR_CHAR = SUBSTRING(@STR_IBAN, @INDEX, 1)

		SET @STR_SOMMA = @STR_SOMMA +
			CASE @STR_CHAR
				WHEN '0' THEN '0'
				WHEN '1' THEN '1'
				WHEN '2' THEN '2'
				WHEN '3' THEN '3'
				WHEN '4' THEN '4'
				WHEN '5' THEN '5'
				WHEN '6' THEN '6'
				WHEN '7' THEN '7'
				WHEN '8' THEN '8'
				WHEN '9' THEN '9'
				WHEN 'A' THEN '10'
				WHEN 'B' THEN '11'
				WHEN 'C' THEN '12'
				WHEN 'D' THEN '13'
				WHEN 'E' THEN '14'
				WHEN 'F' THEN '15'
				WHEN 'G' THEN '16'
				WHEN 'H' THEN '17'
				WHEN 'I' THEN '18'
				WHEN 'J' THEN '19'
				WHEN 'K' THEN '20'
				WHEN 'L' THEN '21'
				WHEN 'M' THEN '22'
				WHEN 'N' THEN '23'
				WHEN 'O' THEN '24'
				WHEN 'P' THEN '25'
				WHEN 'Q' THEN '26'
				WHEN 'R' THEN '27'
				WHEN 'S' THEN '28'
				WHEN 'T' THEN '29'
				WHEN 'U' THEN '30'
				WHEN 'V' THEN '31'
				WHEN 'W' THEN '32'
				WHEN 'X' THEN '33'
				WHEN 'Y' THEN '34'
				WHEN 'Z' THEN '35'
			END

		SET @INDEX = @INDEX + 1
	END

	SET @NEWM = CONVERT(int, LEFT(@STR_SOMMA, 2))
	SET @R = @NEWM % 97

	SET @INDEX = 3
	WHILE @INDEX <= LEN(@STR_SOMMA)
	BEGIN
		SET @NEWM = (10 * @R) + CONVERT(int, SUBSTRING(@STR_SOMMA, @INDEX, 1))
		SET @R = @NEWM % 97

		SET @INDEX = @INDEX + 1
	END

	SET @R = 98 - @R

	SET @STR_IBAN = 'IT' + RIGHT('00' + CONVERT(varchar, @R), 2) + @STR_CIN + @STR_BBAN

	UPDATE
		MG35_CLIFORCC
	SET
		MG35_BBAN = @STR_CIN + @STR_BBAN,
		MG35_IBAN = @STR_IBAN
	WHERE
		CURRENT OF CLIFORCC

	FETCH NEXT FROM CLIFORCC INTO @VAR_DITTA, @VAR_TIPOCF, @VAR_CLIFOR, @VAR_CCFORN, @VAR_CCABI, @VAR_CCCAB, @VAR_BBAN, @VAR_IBAN
END

CLOSE CLIFORCC

DEALLOCATE CLIFORCC
