DECLARE @STR_MESS VARCHAR(MAX)
DECLARE @CODART VARCHAR(25)
DECLARE @DESART VARCHAR(80)
DECLARE @SOGLIA FLOAT
DECLARE @RESIDUO FLOAT
DECLARE cr CURSOR FOR

SELECT RTRIM(CODICE_ARTICOLO), DESCRIZIONE, MIN_ORDINATO, ORDINATO_RESIDUO
FROM OMP_ALERT_SOTTOORDINATO
 
SET @STR_MESS=''
OPEN cr
FETCH NEXT FROM cr INTO @CODART, @DESART, @SOGLIA, @RESIDUO
WHILE @@FETCH_STATUS=0
BEGIN
                SET @STR_MESS = @STR_MESS + ISNULL(@CODART,'') + ' - ' + @DESART + ' - RESIDUO(SCORTA): ' + CAST(@RESIDUO AS VARCHAR) + '('+ CAST(@SOGLIA AS VARCHAR) + ')' + CHAR(13) + CHAR(10) ---Occhio a valori NULL s
FETCH NEXT FROM cr INTO @CODART, @DESART, @SOGLIA, @RESIDUO
END
CLOSE cr
DEALLOCATE cr

Exec sp_send_cdosysmail 'SERVER2003', 'SqlServer@acme.it', 'd.beggi@acme.com', 'm.rustichelli@acme.com', 'Elenco articoli "sotto ordinato"', @STR_MESS
