DECLARE cr CURSOR FOR 
SELECT [R$CODART],[R$COMM]
FROM .....
ORDER BY [R$CODART],[PROGRE]

DECLARE @STR_OLDCODART AS CHAR(25)

DECLARE @STR_CODART AS CHAR(25)
DECLARE @STR_COMM AS VARCHAR(500)

DECLARE @STR_NOTA AS VARCHAR(8000)

OPEN cr

SET @STR_NOTA = ''
FETCH NEXT FROM cr INTO @STR_CODART,@STR_COMM
WHILE @@FETCH_STATUS = 0
BEGIN 
       IF ISNULL(@STR_CODART,'') <> ISNULL(@STR_OLDCODART,'')
       BEGIN
             INSERT INTO ...... (elenco campi) VALUES(@STR_OLDCODART,@STR_NOTA)

             SET @STR_NOTA = ''
       END
       SEt @STR_NOTA = @STR_NOTA + CHAR(13) + CHAR(10) + ISNULL(@STR_COMM,'')
       SET @STR_OLDCODART =@STR_CODART 

       FETCH NEXT FROM cr INTO @STR_CODART,@STR_COMM
END

IF @STR_NOTA  > '' 
BEGIN
       INSERT INTO ...... (elenco cammpi) VALUES(@STR_OLDCODART,@STR_NOTA)
END
