SELECT TOP 1 WITH TIES 
M.MVTIPDOC, M.MVDATDOC, M.MVNUMDOC, D.MVCODART, D.MVQTAMOV, D.MVPREZZO, D.MVSCONT1, D.MVSCONT2, D.MVSCONT3, D.MVSCONT4
FROM STARPDOC_MAST M
INNER JOIN STARPDOC_DETT D ON
D.MVSERIAL=M.MVSERIAL
WHERE M.MVCLADOC = 'FA' AND M.MVTIPCON = 'F' AND D.MVTIPRIG = 'R' AND MVPREZZO <> 0
ORDER BY ROW_NUMBER() OVER (PARTITION BY D.MVCODART ORDER BY M.MVDATDOC DESC)
