DECLARE @STR_MESS VARCHAR(MAX)
DECLARE @DEP CHAR(2)
DECLARE @CODART VARCHAR(25)
DECLARE @DESART VARCHAR(80)
DECLARE @UM1 CHAR(3)
DECLARE @GIACENZA FLOAT
DECLARE cr CURSOR FOR

SELECT  MG70_CODDEP_MG58, RTRIM(MG70_CODART_MG66), MG87_DESCART, MG66_UM1, MG70_QGIACFIS
--, * 
FROM MG70_MAGPROQTA
INNER JOIN MG66_ANAGRART ON
MG66_DITTA_CG18 = MG70_DITTA_CG18 AND
MG66_CODART = MG70_CODART_MG66
INNER JOIN MG87_ARTDESC ON
MG70_DITTA_CG18 = MG87_DITTA_CG18 AND
MG70_CODART_MG66 = MG87_CODART_MG66
WHERE MG70_TIPOPROG = 1 AND MG70_QGIACFIS < 0 AND MG70_CODDEP_MG58 = '0' AND MG70_TIPOQTA = 1

SET @STR_MESS=''
OPEN cr
FETCH NEXT FROM cr INTO @DEP, @CODART, @DESART, @UM1, @GIACENZA
WHILE @@FETCH_STATUS=0
BEGIN
	SET @STR_MESS = @STR_MESS + 'DEP: ' + @DEP + ' - COD: ' + ISNULL(@CODART,'') + ' - ' + @DESART + ' - ' + @UM1 + '('+ CAST(@GIACENZA AS VARCHAR) + ')' + CHAR(13) + CHAR(10) ---Occhio a valori NULL
	FETCH NEXT FROM cr INTO @DEP, @CODART, @DESART, @UM1, @GIACENZA
END
CLOSE cr
DEALLOCATE cr

Exec sp_send_cdosysmail 
'SBS2010', --server mail
'Gamma Enterprise', --from
'rampi@acme.com, birbes@acme.com, bonizzoli@acme.com', --to
'', --ccn
'GAMMA ENTERPRISE - Elenco articoli con giacenze negative', --subject
@STR_MESS --body
