DECLARE @OLD AS VARCHAR(20)
DECLARE @NEW AS VARCHAR(20)

SET @OLD = 'tn.025.001G#05      '
SET @NEW = 'TN.025.001G#05      '

UPDATE    SCALAMVM_DETT
SET       MMKEYSAL = @NEW, MMCODART = @NEW
WHERE     (MMCODICE = @OLD)

UPDATE    SCALADOC_DETT
SET              MVKEYSAL = @NEW, MVCODART = @NEW
WHERE     (MVCODICE = @OLD)

UPDATE    SCALARILEVAZI
SET              DRKEYSAL = @NEW, DRCODART = @NEW
WHERE     (DRCODRIC = @OLD)

UPDATE    SCALAODL_MAST
SET              OLTKEYSA = @NEW, OLTCOART = @NEW
WHERE     (OLTCODIC = @OLD)

UPDATE    SCALAODL_DETT
SET              OLKEYSAL = @NEW, OLCODART = @NEW
WHERE     (OLCODICE = @OLD)

UPDATE    SCALAMAT_PROD
SET              MPCODART = @NEW
WHERE     (MPCODICE = @OLD)

UPDATE    SCALADISTBASE
SET       DBARTCOM = @NEW
WHERE     (DBCODCOM = @OLD)

UPDATE    SCALAKEY_ARTI
SET 		CACODART = @NEW, CADTOBSO = NULL 
WHERE     (CACODART = @OLD)

UPDATE    SCALAPRODINDI
SET 		IDVALATT = @NEW
WHERE     (IDVALATT = @OLD)

UPDATE	SCALACON_TRAD
   SET	COCODART=@NEW
 WHERE	COCODART=@OLD

