DECLARE @ART AS VARCHAR(20)
SET @ART = '10369693'

SELECT M.MVTIPDOC, M.MVNUMDOC, M.MVDATDOC, D.MVCODART, D.MVFLIMPE, D.MVQTAIMP, D.MVQTAEV1, D.MVQTAIMP-D.MVQTAEV1, D.MVFLEVAS, D.MVDATEVA
--, * 
FROM KRISSDOC_MAST M 
INNER JOIN KRISSDOC_DETT D ON 
D.MVSERIAL=M.MVSERIAL
WHERE D.MVFLIMPE='+' 
AND D.MVKEYSAL = @ART 
AND D.MVQTAIMP > 0
AND D.MVFLEVAS <> 'S'

SELECT M.OLCODODL, M.OLTSTATO, M.OLTPROVE, D.OLCODART, D.OLQTAUM1-D.OLQTAEV1, D.OLDATRIC
, D.* 
FROM KRISSODL_MAST M
INNER JOIN KRISSODL_DETT D ON
D.OLCODODL=M.OLCODODL
WHERE D.OLCODART=@ART
AND D.OLFLEVAS<>'S'
--AND D.OLQTASAL >0
