--Query per estrarre il dettaglio dei documenti che compongono il costo medio di acquisto nell'inventario

SELECT M.MVTIPDOC, M.MVDATDOC, M.MVNUMDOC
, D.MVCODART, D.MVQTAUM1, D.MVPREZZO, D.MVVALMAG, D.MVVALRIG, D.MVFLOMAG, D.MVVALMAG/D.MVQTAUM1 AS COSTO_MEDIO
--, * 
FROM NALDODOC_MAST M
INNER JOIN NALDODOC_DETT D ON
M.MVSERIAL=D.MVSERIAL
WHERE M.MVDATDOC < '2018-07-01'
AND D.MVCODART = '1'
AND D.MVCAUMAG IN (SELECT CMCODICE
					FROM NALDOTIP_DOCU
					INNER JOIN NALDOCAM_AGAZ ON
					TDCAUMAG=CMCODICE
					WHERE CMFLAVAL IN ('C','A') AND CMAGGVAL='S')
