SELECT * FROM CIEFFART_ICOL WHERE ARDESART LIKE '%Ø%' OR ARDESSUP LIKE '%Ø%'
SELECT * FROM CIEFFKEY_ARTI WHERE CADESART LIKE '%Ø%' OR CADESSUP LIKE '%Ø%'
SELECT * FROM IRINTTRADARTI WHERE LGDESCOD LIKE '%Ø%' OR LGDESSUP LIKE '%Ø%'
SELECT * FROM CIEFFDOC_DETT WHERE MVDESART LIKE '%Ø%' OR MVDESSUP LIKE '%Ø%'

SELECT * FROM CIEFFART_ICOL WHERE ARDESART LIKE '%°%' OR ARDESSUP LIKE '%°%'
SELECT * FROM CIEFFKEY_ARTI WHERE CADESART LIKE '%°%' OR CADESSUP LIKE '%°%'
SELECT * FROM IRINTTRADARTI WHERE LGDESCOD LIKE '%°%' OR LGDESSUP LIKE '%°%'
SELECT * FROM CIEFFDOC_DETT WHERE MVDESART LIKE '%°%' OR MVDESSUP LIKE '%°%'

SELECT * FROM CIEFFART_ICOL WHERE ARDESART LIKE '%€%' OR ARDESSUP LIKE '%€%'
SELECT * FROM CIEFFKEY_ARTI WHERE CADESART LIKE '%€%' OR CADESSUP LIKE '%€%'
SELECT * FROM IRINTTRADARTI WHERE LGDESCOD LIKE '%€%' OR LGDESSUP LIKE '%€%'
SELECT * FROM CIEFFDOC_DETT WHERE MVDESART LIKE '%€%' OR MVDESSUP LIKE '%€%'

SELECT * FROM CIEFFART_ICOL WHERE ARDESART LIKE '%*%' OR ARDESSUP LIKE '%*%'
SELECT * FROM CIEFFKEY_ARTI WHERE CADESART LIKE '%*%' OR CADESSUP LIKE '%*%'
SELECT * FROM IRINTTRADARTI WHERE LGDESCOD LIKE '%*%' OR LGDESSUP LIKE '%*%'
SELECT * FROM CIEFFDOC_DETT WHERE MVDESART LIKE '%*%' OR MVDESSUP LIKE '%*%'

SELECT * FROM CIEFFART_ICOL WHERE ARDESART LIKE '%&%' OR ARDESSUP LIKE '%&%'
SELECT * FROM CIEFFKEY_ARTI WHERE CADESART LIKE '%&%' OR CADESSUP LIKE '%&%'
SELECT * FROM IRINTTRADARTI WHERE LGDESCOD LIKE '%&%' OR LGDESSUP LIKE '%&%'
SELECT * FROM CIEFFDOC_DETT WHERE MVDESART LIKE '%&%' OR MVDESSUP LIKE '%&%'

SELECT * FROM CIEFFART_ICOL WHERE ARDESART LIKE '%>%' OR ARDESSUP LIKE '%>%'
SELECT * FROM CIEFFKEY_ARTI WHERE CADESART LIKE '%>%' OR CADESSUP LIKE '%>%'
SELECT * FROM IRINTTRADARTI WHERE LGDESCOD LIKE '%>%' OR LGDESSUP LIKE '%>%'
SELECT * FROM CIEFFDOC_DETT WHERE MVDESART LIKE '%>%' OR MVDESSUP LIKE '%>%'

SELECT * FROM CIEFFART_ICOL WHERE ARDESART LIKE '%<%' OR ARDESSUP LIKE '%<%'
SELECT * FROM CIEFFKEY_ARTI WHERE CADESART LIKE '%<%' OR CADESSUP LIKE '%<%'
SELECT * FROM IRINTTRADARTI WHERE LGDESCOD LIKE '%<%' OR LGDESSUP LIKE '%<%'
SELECT * FROM CIEFFDOC_DETT WHERE MVDESART LIKE '%<%' OR MVDESSUP LIKE '%<%'

SELECT * FROM CIEFFART_ICOL WHERE CHARINDEX(CHAR(39), ARDESART,1)>1 OR CHARINDEX(CHAR(39),ARDESSUP, 1)>1
SELECT * FROM CIEFFKEY_ARTI WHERE CHARINDEX(CHAR(39), CADESART,1)>1 OR CHARINDEX(CHAR(39),CADESSUP, 1)>1
SELECT * FROM IRINTTRADARTI WHERE CHARINDEX(CHAR(39), LGDESCOD,1)>1 OR CHARINDEX(CHAR(39),LGDESSUP, 1)>1  
SELECT * FROM CIEFFDOC_DETT WHERE CHARINDEX(CHAR(39), MVDESART,1)>1 OR CHARINDEX(CHAR(39),MVDESSUP, 1)>1

SELECT * FROM CIEFFDOC_DETT WHERE CHARINDEX(CHAR(02), MVDESART,1)>1 OR CHARINDEX(CHAR(02),MVDESSUP, 1)>1


SELECT * FROM CIEFFART_ICOL WHERE ARDESART LIKE '%"%' OR ARDESSUP LIKE '%"%'
SELECT * FROM CIEFFKEY_ARTI WHERE CADESART LIKE '%"%' OR CADESSUP LIKE '%"%'
SELECT * FROM IRINTTRADARTI WHERE LGDESCOD LIKE '%"%' OR LGDESSUP LIKE '%"%'
SELECT * FROM CIEFFDOC_DETT WHERE MVDESART LIKE '%"%' OR MVDESSUP LIKE '%"%'

/*
SELECT * FROM CIEFFART_ICOL WHERE ARDESART LIKE '%$%' OR ARDESSUP LIKE '%$%'
SELECT * FROM CIEFFKEY_ARTI WHERE CADESART LIKE '%$%' OR CADESSUP LIKE '%$%'
SELECT * FROM IRINTTRADARTI WHERE LGDESCOD LIKE '%$%' OR LGDESSUP LIKE '%$%'
SELECT * FROM CIEFFDOC_DETT WHERE MVDESART LIKE '%$%' OR MVDESSUP LIKE '%$%'
*/

--UPDATE CIEFFART_ICOL SET ARDESART=REPLACE(ARDESART, 'Ø', 'D'), ARDESSUP=REPLACE(ARDESSUP, 'Ø', 'D')
--UPDATE CIEFFKEY_ARTI SET CADESART=REPLACE(CADESART, 'Ø', 'D'), CADESSUP=REPLACE(CADESSUP, 'Ø', 'D')
--UPDATE CIEFFTRADARTI SET LGDESCOD=REPLACE(LGDESCOD, 'Ø', 'D'), LGDESSUP=REPLACE(CADESSUP, 'Ø', 'D')
--UPDATE CIEFFDOC_DETT SET MVDESART=REPLACE(MVDESART, 'Ø', 'D'), MVDESSUP=REPLACE(MVDESSUP, 'Ø', 'D')