--Query per estrarre il dettaglio dei documenti che compongono il prezzo medio di vendita nell'inventario

SELECT M.MVTIPDOC, M.MVDATDOC, M.MVNUMDOC
, D.MVCODART, D.MVQTAUM1, D.MVPREZZO, D.MVIMPNAZ, D.MVFLOMAG
--, * 
FROM NALDODOC_MAST M
INNER JOIN NALDODOC_DETT D ON
M.MVSERIAL=D.MVSERIAL
WHERE M.MVDATDOC < '2018-07-01'
AND D.MVCODART = '278'
AND D.MVCAUMAG IN (SELECT CMCODICE
						FROM NALDOTIP_DOCU
						INNER JOIN NALDOCAM_AGAZ ON
						TDCAUMAG=CMCODICE
						WHERE CMFLAVAL IN ('S','V') AND CMAGGVAL='S')
