SELECT TDTIPDOC, TDDESDOC, TDCATDOC, TDFLVEAC, TDCAUMAG, CMDESCRI, CMFLCASC 
FROM KRISSTIP_DOCU
INNER JOIN KRISSCAM_AGAZ ON
CMCODICE=TDCAUMAG
WHERE CMAGGVAL = 'S'
AND CMFLCASC = '+'

--SELECT * FROM KRISSCAM_AGAZ