--CONTROLLO ESISTENZA DI IMPEGNI PER ARTICOLI FANTASMA

SELECT * 
FROM GIM16ART_ICOL 
INNER JOIN GIM16SALDIART ON
SLCODICE=ARCODART
WHERE ARTIPART = 'PH' AND SLQTIPER > 0


--CONTROLLO CICLI DI LAVORAZIONE CON INDICE PREF = '00'

SELECT CLCODART, CLCODDIS, COUNT(CLINDCIC) 
FROM GIM16CIC_MAST 
WHERE CLINDCIC = '00'
GROUP BY CLCODART, CLCODDIS
HAVING COUNT(CLINDCIC) > 1

--CONTROLLO ODL/OCL/ODA CON STATO = '/'

SELECT * 
FROM GIM16ODL_MAST
WHERE OLTSTATO = '/'