--CHIUSURA ODL SU ADHOC CHIUSI IN NETPRO
--SOSTIUIRE I NOMI DELLE TABELLE CON QUELLE DELL'INSTALLAZIONE CLIENTE

--ELENCO ODL DI FASE
SELECT OM.OLCODODL, ID_OPER, OLTSTATO, STATO, OLTPROVE, * 
FROM NETPRO.DBO.OPERAZIONI
INNER JOIN ANGELODL_MAST OM ON
SUBSTRING(OLCODODL, 6, 10)=ID_OPER COLLATE Latin1_General_100_CI_AS
INNER JOIN ANGELODL_DETT OD ON
OM.OLCODODL=OD.OLCODODL
WHERE OLTSTATO <> 'F' AND STATO ='COM'
ORDER BY 1

--AGGIORNAMENTO ODL DI FASE - MATERIALI
UPDATE OD SET OLFLEVAS='S', OLQTASAL=0
FROM NETPRO.DBO.OPERAZIONI
INNER JOIN ANGELODL_MAST OM ON
SUBSTRING(OLCODODL, 6, 10)=ID_OPER COLLATE Latin1_General_100_CI_AS
INNER JOIN ANGELODL_DETT OD ON
OM.OLCODODL=OD.OLCODODL
WHERE OLTSTATO <> 'F' AND STATO ='COM'

--AGGIORNAMENTO ODL DI FASE - TESTATA
UPDATE OM SET OLTSTATO = 'F', OLTFLEVA='S', OLTDTFIN = CAST (SYSDATETIME() AS DATE), OLTQTSAL = 0 
FROM NETPRO.DBO.OPERAZIONI
INNER JOIN ANGELODL_MAST OM ON
SUBSTRING(OLCODODL, 6, 10)=ID_OPER COLLATE Latin1_General_100_CI_AS
INNER JOIN ANGELODL_DETT OD ON
OM.OLCODODL=OD.OLCODODL
WHERE OLTSTATO <> 'F' AND STATO ='COM'

--ELENCO ODL PADRI DA CHIUDERE
SELECT * 
FROM ANGELODL_MAST OM 
WHERE OM.OLTSEODL IS NULL AND OM.OLTSTATO<>'F'
AND NOT EXISTS (SELECT 1 FROM ANGELODL_MAST OM2 WHERE OM2.OLTSEODL=OM.OLCODODL AND OM2.OLTSTATO <> 'F')

--CHIUSURA ODL PADRI
UPDATE OM SET OLTSTATO = 'F', OLTFLEVA='S', OLTDTFIN = CAST (SYSDATETIME() AS DATE), OLTQTSAL = 0 
FROM ANGELODL_MAST OM 
WHERE OM.OLTSEODL IS NULL AND OM.OLTSTATO<>'F'
AND NOT EXISTS (SELECT 1 FROM ANGELODL_MAST OM2 WHERE OM2.OLTSEODL=OM.OLCODODL AND OM2.OLTSTATO <> 'F')

--RICORDARSI DI EFFETTUARE LA RICOSTRUZIONE SALDI AL TERMINE