SELECT * 
FROM SETERODL_MAST M
INNER JOIN SETERODL_DETT D ON
D.OLCODODL=M.OLCODODL
WHERE M.OLTSTATO = 'F'
AND D.OLFLEVAS <> 'S'
AND D.OLQTASAL > 0
AND M.OLTCAMAG = 'PRORD' --SE POSSONO ESSRCI ODL CON CAUSALE "NULL"
AND D.OLCAUMAG = 'PRIMP' --SE SUI MATERIALI POSSONO ESSERCI RIGHE CON CAUSALE "NULL"
