SELECT
10 * ROW_NUMBER() OVER(PARTITION BY PD95_IDDISBA ORDER BY PD96_COMPON, PD96_IDLEGAME) AS PD96_NEWSEQ,
PD96_SEQCOMP,
PD95_CODART_MG66,
PD96_COMPON,
PD95_IDDISBA,
PD96_IDLEGAME
INTO _APEESCAPE
FROM PD95_DISBA
INNER JOIN PD96_LEGAMIDISBA
ON PD96_IDDISBA_PD95 = PD95_IDDISBA
WHERE PD95_DITTA_CG18 = 1
AND PD95_TIPO_DISTINTA = 0

Così facendo ti crea una tabella temporanea (_APEESCAPE) con per ogni legame della distinta base la nuova sequenza componente.
Mettendola in JOIN con la PD96 per PD96_IDLEGAME puoi aggiornare la PD96_SEQCOMPON della PD96 prendendola dalla PD96_NEWSEQ della tabella _APEESCAPE.
